name: Continuous Integration
on: [push]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint CSS
        run: npm run lint:css
      - name: Lint JS
        run: npm run lint:js

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Install dependencies
        run: npm ci
      - name: Test unit
        run: npm run test:unit
      - name: Test build
        run: |
          cd test/project
          npm run build
      - name: Test inspect
        run: |
          cd test/project
          npm run inspect -- build
          npm run inspect -- dev
